#!/bin/bash
GREEN='\033[0;32m'
NC='\033[0m' # No Color
echo "${GREEN}============================================"
echo "${GREEN}|                pre-build"
echo "${GREEN}============================================"
exit 0