#!/bin/bash
echo "============================================"
echo "|                pre-build"
echo "============================================"
echo "Is Docker available?"
docker -v
echo "Is Docker Compose available?"
docker-compose -v
exit 0
